### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by davidvb** [design4use/gb-sketch-segmentcircle#2] opened 2016-01-28 13:29 UTC
Hi there,

Thanks for sharing your cool plugin!
It could prove to be really useful, but with a couple of improvements it could be something I would be using very often as I'm a designer working in finance. 

It would be exceptionally great for making piecharts and diagrams if only:
A: the size of individual segments could be defined in percentages. And..
B: you could make edits later on. Then...
C: if B is possible then it would also make sense if you could set segment colors within the dialog. :)

![A quick mockup:](https://www.evernote.com/l/AATzz2E85MdBWYjN3LtkglAiEWjP1q-6188B/image.jpg)

**Comment by design4use** [comment] 2016-01-28 22:36
Hi thanks for the good ideas. A) is something I can think about. The math would be a bit more complex but I see your use case. Editing later B) is not possible currently since I am not retaining any information once the item is created (scripts are one time deals). I feel C) makes it unnecessarily complex, since the Sketch UI is already much better suited to customizing it with color/styles/borders/fills/etc and I wouldn't want to reproduce this in another UI. This is the reason why I made the segments easily accessible on their own in a folder, so you can style them any which way you want using Sketch.

**Comment by design4use** [comment] 2016-04-04 22:31
Variable values for individual segments are now reality in the just released 2.0 version. Since they are individual segments inside a group they can be easily customized using Sketch. Closing this issue.

**Closed as completed by design4use** 2016-04-04 22:31 UTC
